# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-name: test
        extra-specs: |
          python=3.10.8
          flake8
          pytest
          black
          isort
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check imports with isort
      run: |
        isort --profile black -l 127 -c .
    - name: Check formatting with black
      run: |
        black --target-version=py310 --line-length=127 --include='\.pyi?$' --check .
    - name: Tests
      run: |
        pytest tests/*
